// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLqL86AXM6LVW1SpPcOEoWKnZcB9OH8Us',
    appId: '1:554955054465:web:f5bcf62e50af89e7039c80',
    messagingSenderId: '554955054465',
    projectId: 'autoresq-bbdeb',
    authDomain: 'autoresq-bbdeb.firebaseapp.com',
    storageBucket: 'autoresq-bbdeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAIYFyHcgm2WQKz6Jn1KjAE-kpBEyYOS0',
    appId: '1:554955054465:android:a873c9a772198524039c80',
    messagingSenderId: '554955054465',
    projectId: 'autoresq-bbdeb',
    storageBucket: 'autoresq-bbdeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVGOQY0g4oE-AoTm-SoNiCPoq9w_6-dYk',
    appId: '1:554955054465:ios:97a042a2945a4791039c80',
    messagingSenderId: '554955054465',
    projectId: 'autoresq-bbdeb',
    storageBucket: 'autoresq-bbdeb.firebasestorage.app',
    iosBundleId: 'com.example.miniProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVGOQY0g4oE-AoTm-SoNiCPoq9w_6-dYk',
    appId: '1:554955054465:ios:97a042a2945a4791039c80',
    messagingSenderId: '554955054465',
    projectId: 'autoresq-bbdeb',
    storageBucket: 'autoresq-bbdeb.firebasestorage.app',
    iosBundleId: 'com.example.miniProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLqL86AXM6LVW1SpPcOEoWKnZcB9OH8Us',
    appId: '1:554955054465:web:6690a7523db55ac9039c80',
    messagingSenderId: '554955054465',
    projectId: 'autoresq-bbdeb',
    authDomain: 'autoresq-bbdeb.firebaseapp.com',
    storageBucket: 'autoresq-bbdeb.firebasestorage.app',
  );
}
